travis:
  secure:
    BINSTAR_TOKEN: IVag/jEnQDSEvprtzfPPuTwSXHc8WTk4mFfopR01wDRR0B59Wp9K4wWTkLy68pfZqhfG6PNE24nHZ35Hk7RBdsomGmDTjXYVebOVLhhM0ftkGVPG6ESJguaKh0JdesnZPBg2myJrjRfCbdfwrBnlB5aY0fO0Rb3QFuT/S9kMq7GjgAKuWhgqfvlxQ9NZBpBY/2jAuLeI9v0oVU2r5tprepcQbq7PBWmfXz+bmUVuCyJz0Zt2+LLoO15+mH+4NhYP84lWcHy38g9KIpvfjMk65GpkWt96yVA9CLuq374nEjJAUtMiUnYhMixrgE3cZUi+XenQuYUhwIESxW3ZTu1e+EF5HGa+F3W00HA66aX1qTVJSZVlNIEerkVtaocn4/o09jg2EvNb0oCtXNytuBT3KQd+/sGOKi18b0jaJliwfh1ZHP+d9YvfcCDU5TjR2B3jBVdNhRHW+lSImBkLG1MX6m/uITxlrYiep1bF7GXRmiTQr610iC+e18AtnOcedBkW3WSf4UCxLQDND5CGRwvbPrJXK8sVWHCdYdfIfiRNXXPqDSmTKPzMlF0vu/+zGHjAGcPfWc8PBiXHGLGwra2F+pGepKTa7DqDKIMQpu+9AF4e9VmLw6Lu/7wBhO3ByMMQgxqaqUAdZ8mX4JbutvkBsWUxDl2lfg3ezJPaho5O6S4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
conda_forge_output_validation: true
